version: '3'

services:
  app:
    image: 193635214029.dkr.ecr.eu-central-1.amazonaws.com/raid
    build:
      context: .
    container_name: app
    environment:
      API_KEYS:
    restart: always
    ports:
      - 10101:10101
      - 1024:1024
    volumes:
      - ./settings.yml:/root/settings.yml:ro
      - ./data:/root/data
    command: settings.yml
    networks:
      - alarmbot

  bot:
    build: ./bot
    restart: always
    container_name: bot
    links:
      - app
    networks:
      - alarmbot

networks:
  alarmbot:
    driver: bridge
